[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Compiler settings
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
evm_version = "london"

# RPC endpoints
[rpc_endpoints]
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"
local = "http://localhost:8545"

# Etherscan configuration (simplified)
[etherscan]
lisk_sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Test profile
[profile.test]
verbosity = 2